filter:
    paths: [src/*, test/*]
    excluded_paths: [vendor/*]
before_commands:
    - 'composer install --dev --prefer-source'
tools:
    php_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    php_cs_fixer: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor]
